export const business = {
  name: "VTC MANY",
  legalName: "MANY CARS",
  phone: "+33768146015",
  phoneDisplay: "07 68 14 60 15",
  email: "vtcmany@gmail.com",
  streetAddress: "75 B avenue du Général Leclerc",
  postalCode: "11100",
  city: "Narbonne",
  region: "Occitanie",
  country: "FR",
  director: "Mohamed BOUZID",
  googleMapsUrl: "https://www.google.com/maps?cid=12210354936377896073",
  googleReviewsUrl:
    "https://www.google.com/search?q=VTC+MANY+CHAUFFEUR+PRIV%C3%89+Avis&hl=fr-FR&tbm=lcl&rldimm=12210354936377896073#lkt=LocalPoiReviews",
  whatsappUrl:
    "https://api.whatsapp.com/send/?phone=33768146015&text&type=phone_number&app_absent=0",
  siren: "944 057 009",
  areaServed: [
    "Narbonne",
    "Gruissan",
    "Sigean",
    "Leucate",
    "Coursan",
    "Béziers",
    "Perpignan",
    "Montpellier",
    "Toulouse",
    "Carcassonne",
    "Minervois",
    "Aude",
    "Occitanie",
  ],
} as const;
